import "./Policy.css";

export default function CookiePolicy() {
  return (
    <div className="policy-page">
      <div className="policy-container">
        <div className="policy-header">
          <h1 className="policy-title">Cookie Policy</h1>
          <p className="policy-date">Effective date: 10 June 2025</p>
        </div>

        <div className="policy-content">
          <section className="policy-section">
            <h2>1. Purpose</h2>
            <p>
              The website <strong>neurohiveai.agency</strong> uses cookies and
              LocalStorage for the following purposes:
            </p>
            <ul>
              <li>
                <strong>Essential cookies:</strong> to ensure basic website
                functionality
              </li>
              <li>
                <strong>Analytics:</strong> traffic analytics (Google Analytics
                4 in Consent Mode)
              </li>
              <li>
                <strong>Marketing:</strong> remarketing (Meta Ads, LinkedIn
                Insight Tag)
              </li>
            </ul>
          </section>

          <section className="policy-section">
            <h2>2. Legal Basis</h2>
            <table>
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Legal Basis under Art. 6 GDPR</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Essential cookies</td>
                  <td>Art. 6(1)(f) – Legitimate interest</td>
                </tr>
                <tr>
                  <td>Analytics cookies</td>
                  <td>Art. 6(1)(a) – Consent</td>
                </tr>
                <tr>
                  <td>Marketing cookies</td>
                  <td>Art. 6(1)(a) – Consent</td>
                </tr>
              </tbody>
            </table>
          </section>

          <section className="policy-section">
            <h2>3. Categories and Examples</h2>
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Provider</th>
                  <th>Purpose</th>
                  <th>Expiry</th>
                  <th>Category</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>__cf_bm</td>
                  <td>Cloudflare</td>
                  <td>Bot protection</td>
                  <td>30 minutes</td>
                  <td>Essential</td>
                </tr>
                <tr>
                  <td>_ga</td>
                  <td>Google</td>
                  <td>Traffic analytics</td>
                  <td>2 years</td>
                  <td>Analytics</td>
                </tr>
                <tr>
                  <td>_fbp</td>
                  <td>Meta</td>
                  <td>Remarketing</td>
                  <td>3 months</td>
                  <td>Marketing</td>
                </tr>
              </tbody>
            </table>
          </section>

          <section className="policy-section">
            <h2>4. Managing Cookies</h2>
            <p>
              Upon your first visit, a Cookiebot banner appears with options:
              “Accept”, “Reject”, or “Settings”.
            </p>
            <p>
              You can change your cookie preferences at any time using the
              “Change cookie settings” link in the footer or via your browser
              settings.
            </p>
          </section>

          <section className="policy-section">
            <h2>5. Full Cookie List</h2>
            <p>
              The updated cookie list is automatically generated by Cookiebot
              and available at:
              <br />
              <code>/cookie-scan</code>
            </p>
          </section>

          <section className="policy-section">
            <h2>6. Contact Us</h2>
            <p>For any questions related to this policy, please contact:</p>
            <div className="contact-info">
              <p>
                <strong>NeuroHive AI</strong>
              </p>
              <p>
                Email:{" "}
                <a href="mailto:privacy@neurohiveai.io">
                  privacy@neurohiveai.io
                </a>
              </p>
              <p>Address: ul. Prosta 70, 00-838 Warsaw, Poland</p>
            </div>
          </section>

          <div className="policy-footer">
            <p>
              This cookie policy is part of our Privacy Policy and Terms of Use.
              By using our website, you consent to the use of cookies in
              accordance with this policy.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
